countries:
  - Spain
  - Portugal
  - Italy
  - France
  - Greece
  - Cyprus
  - Malta
  - Turkey
  - USA
  - United States
  - UK
  - United Kingdom
  - Scotland
  - England
  - Wales
  - Ireland

destinations:
  - Tenerife
  - Lanzarote
  - Gran Canaria
  - Majorca
  - Mallorca
  - Benidorm
  - Costa del Sol
  - Algarve
  - Orlando
  - Florida
  - New York
  - Isle of Wight
  - Mediterranean
  - Canary Islands
  - Caribbean
